web/api/config/routes.rb
Rails.application.routes.draw do
  get "/fixed_links/:comment_id/get" => "fixed_links#get", as: 'get_fixed_link'
  get "/favorites" => "favorites#index"
  post "/favorites/:record_type/:record_id/create" => "favorites#create"
  post "/favorites/:record_type/:record_id/destroy" => "favorites#destroy"

  post "/likes/:thread_type/:thread_id/create" => "likes#create"
  post "/likes/:thread_type/:thread_id/destroy" => "likes#destroy"
  get '/notifications/fetch', to: 'notifications#fetch', as: 'fetch_notification'
  resources :notifications
  resources :comments
  get '/calendars/agenda', to: 'calendars#agenda', as: 'agenda_calendar'
  get '/calendars/weekly', to: 'calendars#weekly', as: 'weekly_calendar'
  post '/calendars/create_comment', to: 'calendars#create_comment', as: 'create_calendar_comment'
  resources :calendars
  get 'welcome/index'
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'groups#index'

  devise_for :accounts, controllers: {
    :sessions      => "accounts/sessions",
    :registrations => "accounts/registrations",
    :passwords     => "accounts/passwords"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :groups do
    get '/group_configurations/main', to: 'group_configurations#main'
    get '/group_configurations/theme', to: 'group_configurations#theme'
    get '/group_configurations/mail', to: 'group_configurations#mail'
    get '/group_configurations/event', to: 'group_configurations#event'
    get '/group_configurations/facility', to: 'group_configurations#facility'
    get '/group_configurations/status', to: 'group_configurations#status'
    resources :group_configurations
    patch '/cabinets/:id/revert', to: 'cabinets#revert'
    get '/cabinets/:id/restore/:version', to: 'cabinets#restore', as: 'cabinet_restore'
    resources :cabinets
    resources :boards
    # TODO: これいる？
    get '/projects/new', to: 'projects#new'
    post '/projects', to: 'projects#create'
    get '/projects/:id', to: 'projects#dashboard', as: 'dashboard'
    resources :projects
    resources :invites do
      get '/token/:uuid', :to => 'invites#token'
      get '/error', :to => 'invites#error'
    end
  end
  get '/joined_projects', action: :joined_projects, controller: 'projects', as: 'joined_projects'
  # get '/groups/:group_id/projects/:project_id', to: 'projects#dashboard', as: 'dashboard'
  resources :users
  resources :memos
  patch '/memos/:id/mark_as_read', to: 'memos#mark_as_read', as: 'memo_mark_as_read'
  resources :standard_operations
  patch '/standard_operations/:project_id', to: 'standard_operations#update'
  resources :tasks
  patch '/tasks/:project_id', to: 'tasks#update'
  resources :timers
  patch '/timers/:project_id', to: 'timers#update'
  resources :working_hours
end

web/api/app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :account, dependent: :destroy
end

web/api/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
    if @current_account.id != @setting.account_id
      redirect_to @setting
    end
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:language, :post_per, :week_start, :push_mail, :push_interval)
    end
end

web/api/app/helpers/settings_helper.rb
module SettingsHelper
end

web/api/app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :language %>
    <%= form.text_field :language, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :post_per %>
    <%= form.number_field :post_per, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :week_start %>
    <%= form.text_field :week_start, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :push_mail %>
    <%= form.check_box :push_mail, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :push_interval %>
    <%= form.number_field :push_interval, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '更新する', class: "btn btn-primary" %>
  </div>
<% end %>

web/api/app/views/settings/edit.html.erb
<% provide(:title, '個人設定編集') %>

<main class="container" style="padding-top: 57px;">

  <h1 class="mb-3">個人設定編集</h1>

  <%= render 'form', setting: @setting %>

  <div class="mt-4">
    <%= link_to 'キャンセル', setting_path, class: "btn btn-secondary" %>
  </div>

  <div class="account-delete">
    <%= link_to '退会する', account_registration_path(), :method => :delete, :confirm => 'Are you sure?' %>
  </div>

</main>

web/api/app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Post per</th>
      <th>Week start</th>
      <th>Push mail</th>
      <th>Push interval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.language %></td>
        <td><%= setting.post_per %></td>
        <td><%= setting.week_start %></td>
        <td><%= setting.push_mail %></td>
        <td><%= setting.push_interval %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

web/api/app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

web/api/app/views/settings/show.html.erb
<% provide(:title, '個人設定') %>

<main class="container" style="padding-top: 57px;">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="mb-3">個人設定</h1>

  <% if @current_account.id == @setting.account_id %>
    <%= link_to '個人設定を編集する', edit_setting_path(@setting), class: "btn btn-primary" %>
  <% end %>

  <table class="table mt-4">
    <tbody>
      <tr>
        <th width="200" scope="row">言語</th>
        <td><%= @setting.language %></td>
      </tr>
      <tr>
        <th scope="row">1ページの表示数</th>
        <td><%= @setting.post_per %></td>
      </tr>
      <tr>
        <th scope="row">週の始まり</th>
        <td><%= @setting.week_start %></td>
      </tr>
      <tr>
        <th scope="row">メールでのプッシュ通知</th>
        <td><%= @setting.push_mail %></td>
      </tr>
      <tr>
        <th scope="row">通知する間隔</th>
        <td><%= @setting.push_interval %></td>
      </tr>
    </tbody>
  </table>

</main>