web/api/config/routes.rb
Rails.application.routes.draw do
  get "/fixed_links/:comment_id/get" => "fixed_links#get", as: 'get_fixed_link'
  get "/favorites" => "favorites#index"
  post "/favorites/:record_type/:record_id/create" => "favorites#create"
  post "/favorites/:record_type/:record_id/destroy" => "favorites#destroy"

  post "/likes/:thread_type/:thread_id/create" => "likes#create"
  post "/likes/:thread_type/:thread_id/destroy" => "likes#destroy"
  get '/notifications/fetch', to: 'notifications#fetch', as: 'fetch_notification'
  resources :notifications
  resources :comments
  get '/calendars/agenda', to: 'calendars#agenda', as: 'agenda_calendar'
  get '/calendars/weekly', to: 'calendars#weekly', as: 'weekly_calendar'
  post '/calendars/create_comment', to: 'calendars#create_comment', as: 'create_calendar_comment'
  resources :calendars
  get 'welcome/index'
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'groups#index'

  devise_for :accounts, controllers: {
    :sessions      => "accounts/sessions",
    :registrations => "accounts/registrations",
    :passwords     => "accounts/passwords"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :groups do
    get '/group_configurations/main', to: 'group_configurations#main'
    get '/group_configurations/theme', to: 'group_configurations#theme'
    get '/group_configurations/mail', to: 'group_configurations#mail'
    get '/group_configurations/event', to: 'group_configurations#event'
    get '/group_configurations/facility', to: 'group_configurations#facility'
    get '/group_configurations/status', to: 'group_configurations#status'
    resources :group_configurations
    patch '/cabinets/:id/revert', to: 'cabinets#revert'
    get '/cabinets/:id/restore/:version', to: 'cabinets#restore', as: 'cabinet_restore'
    resources :cabinets
    resources :boards
    # TODO: これいる？
    get '/projects/new', to: 'projects#new'
    post '/projects', to: 'projects#create'
    get '/projects/:id', to: 'projects#dashboard', as: 'dashboard'
    resources :projects
    resources :invites do
      get '/token/:uuid', :to => 'invites#token'
      get '/error', :to => 'invites#error'
    end
  end
  get '/joined_projects', action: :joined_projects, controller: 'projects', as: 'joined_projects'
  # get '/groups/:group_id/projects/:project_id', to: 'projects#dashboard', as: 'dashboard'
  resources :users
  resources :memos
  patch '/memos/:id/mark_as_read', to: 'memos#mark_as_read', as: 'memo_mark_as_read'
  resources :standard_operations
  patch '/standard_operations/:project_id', to: 'standard_operations#update'
  resources :tasks
  patch '/tasks/:project_id', to: 'tasks#update'
  resources :timers
  patch '/timers/:project_id', to: 'timers#update'
  resources :working_hours
end

web/api/app/models/user.rb
class User < ApplicationRecord
  belongs_to :account, dependent: :destroy
end

web/api/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
    if @current_account.id != @user.account_id
      redirect_to @user
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:image]
      # TODO: ファイル名の規則
      @user.image_name = "#{@current_account.user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name, :company, :birthday, :url, :address, :introduction, :image_name
      )
    end
end

web/api/app/helpers/users_helper.rb
module UsersHelper
end

web/api/app/views/users/_form.html.erb
<%= form_with(model: user, local: true, multipart: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group d-flex align-items-end">
    <div class="profile_image">
      <img id="uploaded-image" src="<%= "/user_images/#{@current_account.user.image_name}" %>" width="96">
    </div>
    <div class="ml-4">
      <label class="mb-0">
        <span class="btn btn-primary">
          Choose File
          <input type="file" name="image" id="image-uploader" style="display:none">
        </span>
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :birthday %>
    <%= form.date_field :birthday, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :introduction %>
    <%= form.text_area :introduction, class: "form-control" %>
  </div>

  <div class="actions mt-4">
    <%= form.submit '更新する', class: "btn btn-primary" %>
  </div>
<% end %>

web/api/app/views/users/edit.html.erb
<% provide(:title, 'プロフィール編集') %>

<main class="container" style="padding-top: 57px;">

  <h1 class="mb-3">プロフィール編集</h1>

  <%= render 'form', user: @user %>

  <div class="mt-4">
    <%= link_to 'キャンセル', user_path, class: "btn btn-secondary" %>
  </div>

</main>

web/api/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

web/api/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

web/api/app/views/users/show.html.erb
<% provide(:title, 'プロフィール') %>

<main class="container" style="padding-top: 57px;">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="mb-3">プロフィール</h1>

  <% if @current_account.id == @user.account_id %>
    <%= link_to 'プロフィールを編集する', edit_user_path(@user), class: "btn btn-primary" %>
  <% end %>

  <div class="profile_image mt-5">
    <img src="<%= "/user_images/#{@user.image_name}" %>" width="96">
  </div>

  <table class="table mt-4">
    <tbody>
      <tr>
        <th width="200" scope="row">名前</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th scope="row">会社名</th>
        <td><%= @user.company %></td>
      </tr>
      <tr>
        <th scope="row">誕生日</th>
        <td><%= @user.birthday %></td>
      </tr>
      <tr>
        <th scope="row">住所</th>
        <td><%= @user.address %></td>
      </tr>
      <tr>
        <th scope="row">URL</th>
        <td><%= @user.url %></td>
      </tr>
      <tr>
        <th scope="row">自己紹介</th>
        <td><%= @user.introduction %></td>
      </tr>
    </tbody>
  </table>

</main>