web/api/config/routes.rb
Rails.application.routes.draw do
  get "/fixed_links/:comment_id/get" => "fixed_links#get", as: 'get_fixed_link'
  get "/favorites" => "favorites#index"
  post "/favorites/:record_type/:record_id/create" => "favorites#create"
  post "/favorites/:record_type/:record_id/destroy" => "favorites#destroy"

  post "/likes/:thread_type/:thread_id/create" => "likes#create"
  post "/likes/:thread_type/:thread_id/destroy" => "likes#destroy"
  get '/notifications/fetch', to: 'notifications#fetch', as: 'fetch_notification'
  resources :notifications
  resources :comments
  get '/calendars/agenda', to: 'calendars#agenda', as: 'agenda_calendar'
  get '/calendars/weekly', to: 'calendars#weekly', as: 'weekly_calendar'
  post '/calendars/create_comment', to: 'calendars#create_comment', as: 'create_calendar_comment'
  resources :calendars
  get 'welcome/index'
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'groups#index'

  devise_for :accounts, controllers: {
    :sessions      => "accounts/sessions",
    :registrations => "accounts/registrations",
    :passwords     => "accounts/passwords"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :groups do
    get '/group_configurations/main', to: 'group_configurations#main'
    get '/group_configurations/theme', to: 'group_configurations#theme'
    get '/group_configurations/mail', to: 'group_configurations#mail'
    get '/group_configurations/event', to: 'group_configurations#event'
    get '/group_configurations/facility', to: 'group_configurations#facility'
    get '/group_configurations/status', to: 'group_configurations#status'
    resources :group_configurations
    patch '/cabinets/:id/revert', to: 'cabinets#revert'
    get '/cabinets/:id/restore/:version', to: 'cabinets#restore', as: 'cabinet_restore'
    resources :cabinets
    resources :boards
    # TODO: これいる？
    get '/projects/new', to: 'projects#new'
    post '/projects', to: 'projects#create'
    get '/projects/:id', to: 'projects#dashboard', as: 'dashboard'
    resources :projects
    resources :invites do
      get '/token/:uuid', :to => 'invites#token'
      get '/error', :to => 'invites#error'
    end
  end
  get '/joined_projects', action: :joined_projects, controller: 'projects', as: 'joined_projects'
  # get '/groups/:group_id/projects/:project_id', to: 'projects#dashboard', as: 'dashboard'
  resources :users
  resources :memos
  patch '/memos/:id/mark_as_read', to: 'memos#mark_as_read', as: 'memo_mark_as_read'
  resources :standard_operations
  patch '/standard_operations/:project_id', to: 'standard_operations#update'
  resources :tasks
  patch '/tasks/:project_id', to: 'tasks#update'
  resources :timers
  patch '/timers/:project_id', to: 'timers#update'
  resources :working_hours
end

web/api/app/views/dashboard_modules/_comments.html.erb
<div class="card mb-3">
  <div class="card-header text-white bg-dark">コメント</div>
  <div class="card-body">
    <%= form_tag({controller: 'comments', action: 'create'}, { remote: true, class: 'js_memos-form'}) do %>
      <div class="field mb-2">
        <%= text_area_tag :body, nil, {class: 'form-control', placeholder: "Waiting comment..", style: 'height: 180px;'} %>
      </div>
      <%= hidden_field_tag :parent_id, @project.id %>
      <%= hidden_field_tag :parent_type, 'project' %>
      <%= submit_tag 'コメントする', {class: "btn btn-info my-2"} %>
    <% end %>
    <div id="js_memo" class="mt-3 list-group">
      <% @comments.each do |comment| %>
        <div class="list-group-item">
          <div class="py-2 d-flex w-100 justify-content-between">
            <div>
              <img src="/user_images/<%= User.find_by(id: comment.user_id).image_name %>" width="30">
              <%= comment.id %>: <%= User.find_by(id: comment.user_id).name %> <%= comment.created_at.strftime("%Y/%m/%d (#{@wd[comment.created_at.wday]}) %H:%M") %>
            </div>
            <small><a href="<%= comment_path(comment) %>" class="float-right" data-method="delete" data-confirm="本当に削除しますか？">削除</a></small>
          </div>
          <div class="py-2"> <%= comment.body %> </div>
          <div class="pt-2 border-top"><a href="">♥ <small>いいね！</small></a></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

web/api/app/views/dashboard_modules/_memos.html.erb
<div class="card mb-3">
  <div class="card-header text-white bg-dark">コメント
    <a class="float-right text-white" href="#" data-toggle="modal" data-target="#memoModal"><i class="fas fa-plus"></i></a>
  </div>
  <div class="card-body">
    <%= form_tag({controller: 'memos', action: 'create'}, { remote: true, class: 'js_memos-form'}) do %>
      <div class="field mb-2">
        <%= text_area_tag :body, nil, {class: 'form-control', placeholder: "Waiting comment..", style: 'height: 180px;'} %>
      </div>
      <%= hidden_field_tag :project_id, @project.id %>
      <%= submit_tag 'Add', {class: "btn btn-info"} %>
    <% end %>
    <div id="js_memo" class="mt-3 list-group">
      <% @memos.each do |m| %>
        <div class="list-group-item">
          <div class="py-2 d-flex w-100 justify-content-between">
            <div>
              <img src="https://placehold.jp/30x30.png" width="30">
              <%= m.id %>: ユーザー名 <%= m.created_at %>
            </div>
            <small><a href="/memos/<%= m.id %>/edit" class="float-right">編集</a></small>
          </div>
          <div class="py-2"> <%= m.body %> </div>
          <div class="pt-2 border-top"><a href="">♥ <small>いいね！</small></a></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

web/api/app/views/dashboard_modules/_standard_operations.html.erb
<div class="card mb-3">
  <div class="card-header text-white bg-dark">
    <a class="text-white" data-toggle="collapse" href="#standard-operation" role="button" aria-expanded="false" aria-controls="standard-operation">
      標準作業
    </a>
    <a class="float-right text-white js_standard-operations-form-activate-btn" href="javascript:void(0);"><i class="fas fa-plus"></i></a>
  </div>
  <div class="collapse show" id="standard-operation">
    <div class="card-body">
      <% StandardOperation.where(project_id: @project.id).each do |so| %>
        <%= form_tag({controller: 'standard_operations', action: 'update'}, { method: 'patch', authenticity_token: true, remote: true, id: "form_standard_operations", class: 'was-validated'}) do %>
          <div class="custom-control custom-checkbox mb-1">
            <input type="checkbox" class="custom-control-input" id="standard_operation_id<%= so.id %>" name="state" value="1" onchange='this.form.submit()' <%= 'checked' if so.state %> required>
            <label class="custom-control-label" for="standard_operation_id<%= so.id %>"><%= so.task %></label>
            <span class="float-right"><%= link_to raw('<i class="fas fa-times"></i>'), standard_operation_path(so), {remote: true, :method => :delete, :class => 'text-dark'} %></span>
          </div>
          <%= hidden_field_tag :standard_operation_id, so.id %>
        <% end %>
      <% end %>

      <%= form_tag({controller: 'standard_operations', action: 'create'}, { remote: true, class: 'js_standard-operations-form'}) do %>
        <div class="field mt-3 mb-2">
          <%= label_tag :task, nil, {class: 'sr-only'} %>
          <%= text_field_tag :task, nil, {class: 'form-control', placeholder: "task"} %>
        </div>
        <div class="actions">
          <%= submit_tag 'Add', {class: "btn btn-sm btn-info"} %>
        </div>
        <%= hidden_field_tag :project_id, @project.id %>
      <% end %>

    </div>
  </div>
</div>

web/api/app/views/dashboard_modules/_tasks.html.erb
<div class="card mb-3">
  <div class="card-header text-white bg-dark">SUB TASK<a class="float-right text-white" href="#"><i class="fas fa-plus"></i></a></div>
  <div class="card-body">
    <div id="form_tasks">
      <% Task.where(project_id: @project.id).each do |t| %>
        <%= form_tag({controller: 'tasks', action: 'update'}, { method: 'patch', authenticity_token: true, remote: true, class: ''}) do %>
          <div class="custom-control custom-checkbox mb-1">
            <input type="checkbox" class="custom-control-input" id="task_id<%= t.id %>" name="state" value="1" onchange='this.form.submit()' <%= 'checked' if t.state %>>
            <label class="custom-control-label" for="task_id<%= t.id %>"><%= t.name %></label>
            <!--
            <span class="ml-2 js_count">
              <span style="font-size: 0.8rem;">
                <%# TODO: カウント処理 %>
                <%= get_formatted_time(t.id, @project.id).html_safe %>
              </span>
            -->
              <%= hidden_field_tag :working_hour_id, t.working_hour.id %>
              <%= hidden_field_tag :task_id, t.id %>
            <!--
            </span>
            <span class="float-right"><%= link_to raw('<i class="fas fa-times"></i>'), task_path(t), {remote: true, :method => :delete, :class => 'text-dark'} %></span>
            -->
          </div>
        <% end %>
      <% end %>
    </div>

    <%= form_tag({controller: 'tasks', action: 'create'}, { remote: true, class: 'js_tasks-form'}) do %>
      <div class="field mt-3 mb-2">
        <%= label_tag :name, nil, {class: 'sr-only'} %>
        <%= text_field_tag :name, nil, {class: 'form-control', placeholder: "Waiting task.."} %>
      </div>
      <div class="actions">
        <%= submit_tag 'Add', {class: "btn btn-sm btn-info"} %>
      </div>
      <%= hidden_field_tag :project_id, @project.id %>
    <% end %>
  </div>
</div>

web/api/app/views/dashboard_modules/_timers.html.erb
<div class="card mb-3">
  <div class="card-header text-white bg-dark">作業時間カウント<a class="float-right text-white" data-toggle="modal" data-target="#timerModal" href="javascript:void(0);"><i class="far fa-edit"></i></a></div>
  <div class="card-body">
    <div class="m_timer">
      <div class="row">
        <%= select_tag 'page[name]', options_for_select([["Railsの基礎", "rails_base"], ["Rubyの基礎", "ruby_base"]]) %>
      </div>
      <div class="row">
        <div class="mx-auto badge badge-light py-2 px-3 border">進行中タスク名：〇〇〇〇〇〇〇〇〇〇</div>
      </div>
      <div class="row">
        <div class="col mr-3">
          <div id="id_disp" class="m_timer__num mx-auto row justify-content-around">
            <div class="hour">00</div>:<div class="min">03</div>:<div class="sec">00</div>
          </div>
          <div class="m_timer__label row justify-content-around text-center">
            <div class="col">HOUR</div><div class="col">MIN</div><div class="col">SEC</div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
            <div class="m_timer__btns w-75 mx-auto py-3 row justify-content-between">
              <div>
                <a href="javascript:void(0);" id="id_start" class="text-dark" data-toggle="tooltip" data-placement="top" title="開始する"><i class="fas fa-play-circle fa-2x"></i></a>
              </div>
              <div>
                <a href="javascript:void(0);" id="id_stop" class="text-danger" data-toggle="tooltip" data-placement="top" title="停止する"><i class="fas fa-stop-circle fa-2x"></i></a>
              </div>
              <div>
                <a href="javascript:void(0);" id="id_clear" class="text-dark" data-toggle="tooltip" data-placement="top" title="初期化する"><i class="fas fa-undo-alt fa-2x"></i></a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="timerModal" tabindex="-1" role="dialog" aria-labelledby="timerModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="timerModalLabel">Add Memo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag({controller: 'timers', action: 'update'}, { method: 'patch', remote: true, class: 'js_timers-form'}) do %>
        <div class="modal-body">
          <div class="form-row">
            <div class="col">
              <%= label_tag :h, nil, {class: ''} %>
              <%= number_field_tag :h, nil, { min: 00, max: 99, step: 1, class: 'form-control', placeholder: "Waiting hours..", value: @project.timer.h } %>
            </div>
            <div class="col">
              <%= label_tag :m, nil, {class: ''} %>
              <%= number_field_tag :m, nil, { min: 00, max: 59, step: 1, class: 'form-control', placeholder: "Waiting minutes..", value: @project.timer.m } %>
            </div>
            <div class="col">
              <%= label_tag :s, nil, {class: ''} %>
              <%= number_field_tag :s, nil, { min: 00, max: 59, step: 1, class: 'form-control', placeholder: "Waiting seconds..", value: @project.timer.s } %>
            </div>
          </div>
          <%= hidden_field_tag :project_id, @project.id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Add', {class: "btn btn-info"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>