web/api/config/routes.rb
Rails.application.routes.draw do
  get "/fixed_links/:comment_id/get" => "fixed_links#get", as: 'get_fixed_link'
  get "/favorites" => "favorites#index"
  post "/favorites/:record_type/:record_id/create" => "favorites#create"
  post "/favorites/:record_type/:record_id/destroy" => "favorites#destroy"

  post "/likes/:thread_type/:thread_id/create" => "likes#create"
  post "/likes/:thread_type/:thread_id/destroy" => "likes#destroy"
  get '/notifications/fetch', to: 'notifications#fetch', as: 'fetch_notification'
  resources :notifications
  resources :comments
  get '/calendars/agenda', to: 'calendars#agenda', as: 'agenda_calendar'
  get '/calendars/weekly', to: 'calendars#weekly', as: 'weekly_calendar'
  post '/calendars/create_comment', to: 'calendars#create_comment', as: 'create_calendar_comment'
  resources :calendars
  get 'welcome/index'
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'groups#index'

  devise_for :accounts, controllers: {
    :sessions      => "accounts/sessions",
    :registrations => "accounts/registrations",
    :passwords     => "accounts/passwords"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :groups do
    get '/group_configurations/main', to: 'group_configurations#main'
    get '/group_configurations/theme', to: 'group_configurations#theme'
    get '/group_configurations/mail', to: 'group_configurations#mail'
    get '/group_configurations/event', to: 'group_configurations#event'
    get '/group_configurations/facility', to: 'group_configurations#facility'
    get '/group_configurations/status', to: 'group_configurations#status'
    resources :group_configurations
    patch '/cabinets/:id/revert', to: 'cabinets#revert'
    get '/cabinets/:id/restore/:version', to: 'cabinets#restore', as: 'cabinet_restore'
    resources :cabinets
    resources :boards
    # TODO: これいる？
    get '/projects/new', to: 'projects#new'
    post '/projects', to: 'projects#create'
    get '/projects/:id', to: 'projects#dashboard', as: 'dashboard'
    resources :projects
    resources :invites do
      get '/token/:uuid', :to => 'invites#token'
      get '/error', :to => 'invites#error'
    end
  end
  get '/joined_projects', action: :joined_projects, controller: 'projects', as: 'joined_projects'
  # get '/groups/:group_id/projects/:project_id', to: 'projects#dashboard', as: 'dashboard'
  resources :users
  resources :memos
  patch '/memos/:id/mark_as_read', to: 'memos#mark_as_read', as: 'memo_mark_as_read'
  resources :standard_operations
  patch '/standard_operations/:project_id', to: 'standard_operations#update'
  resources :tasks
  patch '/tasks/:project_id', to: 'tasks#update'
  resources :timers
  patch '/timers/:project_id', to: 'timers#update'
  resources :working_hours
end

web/api/app/models/group.rb
class Group < ApplicationRecord
  has_many :accounts, through: :group_accounts
  has_many :group_accounts
  accepts_nested_attributes_for :group_accounts

  has_many :projects, through: :group_projects
  has_many :group_projects
  accepts_nested_attributes_for :group_projects

  has_many :calendar_groups
  has_many :calendars, through: :calendar_groups

  has_many :boards, dependent: :destroy
  has_many :cabinets, dependent: :destroy

  scope :with_project, -> { joins(:projects) }
  scope :search_with_group_id, ->(group_id) { where(group_id: group_id) }

  def self.get_all_updates(current_user_id)
    pu = Notification.where(user_id: current_user_id).order(id: :desc)
    grouped = pu.group_by { |item| item.parent_type }
    comment_group = pu.group_by { |item| item.thread_type }['comment']

    project_updates = Hash.new { |h, k| h[k] = {} }
    calendar_updates = Hash.new { |h, k| h[k] = {} }

    if grouped["project"].present?
      grouped["project"].each do |item|
        project_updates[item.parent_id.to_s] = []
        if item.parent_type == item.thread_type
          project_updates[item.parent_id.to_s].push(item)
        end
      end
      # raise
    end

    if grouped["calendar"].present?
      grouped["calendar"].each do |item|
        calendar_updates[item.parent_id.to_s] = []
        if item.parent_type == item.thread_type
          calendar_updates[item.parent_id.to_s].push(item)
        end
      end
      # raise
    end

    if comment_group.present?
      comment_group.each do |item|
        comment = Comment.find_by(id: item.thread_id)
        parent_type = Comment.find_by(id: item.thread_id).parent_type
        if parent_type == 'project'
          parent = Object.const_get(parent_type.classify).find_by(id: comment.parent_id)
          project_updates[parent.id.to_s].push(comment)
        end

        if parent_type == 'calendar'
          parent = Object.const_get(parent_type.classify).find_by(id: comment.parent_id)
          calendar_updates[parent.id.to_s].push(comment)
        end
        # raise
      end
    end
    
    updates = Hash.new
    updates = project_updates.merge(calendar_updates)
    # raise
  end

  def self.get_project_updates(current_user_id, group_id = nil)
    pu = Notification.where(user_id: current_user_id).order(id: :desc)
    grouped = pu.group_by { |item| item.parent_type }
    comment_group = pu.group_by { |item| item.thread_type }['comment']

    project_updates = Hash.new { |h, k| h[k] = {} }

    if grouped["project"].present?
      grouped["project"].each do |item|
        project_updates[item.parent_id.to_s] = []
        if item.parent_type == item.thread_type
          project_updates[item.parent_id.to_s].push(item)
        end
      end
      # raise
    end

    if comment_group.present?
      comment_group.each do |item|
        comment = Comment.find_by(id: item.thread_id)
        parent_type = Comment.find_by(id: item.thread_id).parent_type
        if parent_type == 'project'
          parent = Object.const_get(parent_type.classify).find_by(id: comment.parent_id)
          project_updates[parent.id.to_s].push(comment)
        end
      end
    end

    # groupに絞る
    # TODO: リファクタリングもっと事前に処理できるはず
    if group_id.present?
      project_updates.each do |update|
        project = Project.find_by(id: update[0], group_id: group_id)
        project_updates.delete(update[0]) if project.blank?
      end
    end

    project_updates
  end

  def self.get_calendar_updates(current_user_id, group_id = nil)
    pu = Notification.where(user_id: current_user_id).order(id: :desc)
    grouped = pu.group_by { |item| item.parent_type }
    comment_group = pu.group_by { |item| item.thread_type }['comment']

    calendar_updates = Hash.new { |h, k| h[k] = {} }

    if grouped["calendar"].present?
      grouped["calendar"].each do |item|
        calendar_updates[item.parent_id.to_s] = []
        if item.parent_type == item.thread_type
          calendar_updates[item.parent_id.to_s].push(item)
        end
      end
      # raise
    end

    if comment_group.present?
      comment_group.each do |item|
        comment = Comment.find_by(id: item.thread_id)
        parent_type = Comment.find_by(id: item.thread_id).parent_type
        if parent_type == 'calendar'
          parent = Object.const_get(parent_type.classify).find_by(id: comment.parent_id)
          calendar_updates[parent.id.to_s].push(comment)
        end
        # raise
      end
    end

    # groupに絞る
    # TODO: リファクタリングもっと事前に処理できるはず
    if group_id.present?
      calendar_updates.each do |update|
        calendar = Calendar.find_by(id: update[0])
        if calendar.groups.pluck(:id).include?(group_id.to_i) == false
          calendar_updates.delete(update[0])
        end
      end
    end

    calendar_updates
  end
end

web/api/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_account!, only: [:index]
  before_action :get_current_account
  before_action :joined_groups
  before_action :joined_current_group?, except: [:index, :new, :create]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # root
  # GET /groups
  # GET /groups.json
  def index
    # TODO: calendarのアップデートが考慮されていない
    all_updates = Group.get_all_updates(current_user_id)
    @group_all_updates = Hash.new { |h,k| h[k] = {} }
    all_updates.each do |parent_id, comments|
      project = Project.find_by(id: parent_id)
      next if project.blank?
      group_id = project.group_id
      @group_all_updates[group_id.to_s][parent_id] = comments
    end
    # raise

    # project_updates = Group.get_project_updates(current_user_id)
    # @group_project_updates = Hash.new { |h,k| h[k] = {} }
    # project_updates.each do |parent_id, comments|
    #   group_id = Project.find_by(id: parent_id).group_id
    #   @group_project_updates[group_id.to_s][parent_id] = comments
    # end
    # raise

    @wd = ["日", "月", "火", "水", "木", "金", "土"]
    if params[:starting_point]
      starting_point = params[:starting_point].split('-').map {|item|
        item.to_i
      }
      @time = Time.new(starting_point[0], starting_point[1], starting_point[2])
    else
      @time = Time.zone.now
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @project_updates = Group.get_project_updates(current_user_id, params[:id])
    @calendar_updates = Group.get_calendar_updates(current_user_id, params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    # TODO: association?
    if @group.save
      @group_account = GroupAccount.new(
        group_id: @group.id,
        account_id: @current_account.id
      )
    end

    respond_to do |format|
      if @group_account.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(
        :name,
        :create_account_id,
        :notice,
        :invitation_authority,
        :icon_img,
      )
    end

    def get_current_account
      @current_account = current_account
      if @current_account.blank?
        redirect_to new_account_session_path
      end
    end

    def joined_groups
      if @current_account.blank?
        redirect_to new_account_session_path
      end
      # TODO: not work??
      ids = @current_account.group_accounts.where(account_id: @current_account.id).pluck(:group_id)
      # raise
      @joined_groups = Group.where(id: ids)
    end

    def joined_current_group?
      if @joined_groups.pluck(:id).include?(params[:id].to_i) == false
        raise "Don't have authority."
      end
    end
end

web/api/app/helpers/groups_helper.rb
module GroupsHelper

end

web/api/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, { class: 'form-control', placeholder: "name" } %>
  </div>

  <div class="form-group">
    <%= form.label :notice %>
    <%= form.text_area :notice, { class: 'form-control', style: 'height:120px;' } %>
  </div>

  <div class="form-group">
    <%= form.label :invitation_authority %>
    <%= form.select :invitation_authority, ['管理者のみが招待可能', 'すべてのメンバーが招待可能'], {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.label :icon_img %>
    <%= form.file_field :icon_img, { class: 'form-control' } %>
  </div>

  <%= form.hidden_field :create_account_id, { value: @current_account.id } %>

  <div class="actions">
    <%= form.submit '保存する', { class: "btn btn-info" } %>
  </div>
<% end %>

web/api/app/views/groups/add_member.html.erb
<% provide(:title, 'メンバーを招待する') %>

<main class="container" style="padding-top: 57px">
  <h2>メンバーを招待する</h2>
  <div class="mt-5">

    <p>グループに招待する知人のメールアドレスを入力してください。</p>

    <%= form_for @group, :url => {:action => 'invite_member'} do |f| %>
      <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label 'メールアドレス' %>
        <%= f.text_field :mail, { class: 'form-control', placeholder: "benzoh.wada@gmail.com" } %>
      </div>

      <%= f.hidden_field :from, { value: @current_account.id } %>

      <div class="actions">
        <%= f.submit '内容確認へ', { class: "btn btn-info" } %>
      </div>
    <% end %>

  </div>
</main>

web/api/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

web/api/app/views/groups/index.html.erb
<% provide(:title, 'ホーム') %>

<main class="container-fluid" style="padding-top: 57px">
  <% flash.each do |key, value| %>
    <% key = 'success' if key == 'notice' %>
    <%= content_tag(:div, value, class: "text-center alert alert-#{key}") %>
  <% end %>
  <div class="row">
    <div class="col-2">
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">アカウント情報</div>
        <div class="card-body d-flex">
          <img src="<%= "/user_images/#{@current_account.user.image_name}" %>" width="50" height="50">
          <div class="ml-2">
            <%= link_to @current_account.user.name, user_path(@current_account.user.id) %>
            <div>
              <a href="#"><i class="fab fa-twitter-square"></i></a>
              <a href="#"><i class="fab fa-facebook-square"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">グループ一覧
          <small class="float-right" style="padding: 2px 0;">
            <a class="text-white" href="javascript:alert('未実装です');">未読のみ</a>｜<a class="text-white" href="javascript:alert('未実装です');">すべて</a>
          </small>
        </div>
        <div class="card-body">
          <% if @joined_groups.blank? %>
            参加しているグループがありません
          <% else %>
            <% @joined_groups.each do |group| %>
              <div class="my-2">
                <img src="https://placehold.jp/30x30.png" alt="">
                <%= link_to group.name, group_path(group) %>
              </div>
            <% end %>
          <% end %>
          <hr>
          <div class="py-1">
            <%= link_to 'グループを作る', new_group_path %>
          </div>
          <div class="py-1">
            <%= link_to '参加グループの設定', 'javascript:alert("未実装です")' %>
          </div>
          <%# <div>
            <a href="#">参加グループ設定</a>
          </div> %>
        </div>
      </div>
    </div>

    <div class="col-10">
      <div class="alert alert-light border" role="alert">
        <div class="text-dark"><strong>お知らせ</strong></div>
        <hr>
        <ul class="mb-0">
          <% if @current_account.name.blank? %>
            <li><%= link_to 'プロフィールを編集してください。', user_path(@current_account.user.id) %>
            </li>
          <% end %>
          <li><a href="">色は匂へど散りぬるを、我が世たれぞ常ならむ。有為の奥山今日越えて、浅き夢見じ、酔ひもせず。</a></li>
          <li><a href="">色は匂へど散りぬるを、我が世たれぞ常ならむ。有為の奥山今日越えて、浅き夢見じ、酔ひもせず。</a></li>
        </ul>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">週間予定</div>
        <div class="card-body">
          <%= render 'home_modules/weekly_calendar' %>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">参加グループ</div>
        <div class="card-body">
          <div class="row justify-content-start">
            <% @joined_groups.each do |group| %>
              <div class="col-1 text-center">
                <img src="https://placehold.jp/50x50.png" alt=""><br>
                <%= link_to group.name, group_path(group) %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">新着一覧</div>
        <div class="card-body">
          <%# TODO: 参加グループの更新履歴表示 %>
          <% if @group_all_updates.blank? %>
            <span>更新はありません。</span>
          <% else %>
            <%# TODO: グループごとのループ処理 %>
            <%= render partial: "_group_modules/index_updates", locals: {updates: @group_all_updates} %>
          <% end %>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="col-2">
          <strong>HippoWorksについて</strong>
          <ul>
            <li><a href="#">hoge</a></li>
            <li><a href="#">fuga</a></li>
          </ul>
        </div>
        <div class="col-2">
          <strong>もっと活用する</strong>
          <ul>
            <li><a href="#">hoge</a></li>
            <li><a href="#">fuga</a></li>
          </ul>
        </div>
        <div class="col-2">
          <strong>アカウント</strong>
          <ul>
            <li><a href="#">個人設定</a></li>
            <li><a href="#">ログアウト</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</main>

web/api/app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>

<main class="container" style="padding-top: 57px">
  <h2>グループを作成</h2>
  <div class="mt-5">
    <%= render 'form', group: @group %>
  </div>
</main>

web/api/app/views/groups/show.html.erb
<% provide(:title, 'groups#show') %>

<main class="container-fluid" style="padding-top: 16px;">

  <% flash.each do |key, value| %>
    <% key = 'success' if key == 'notice' %>
    <%= content_tag(:div, value, class: "text-center alert alert-#{key}") %>
  <% end %>

  <div class="row">
    <div class="col-2">
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">メンバーへのお知らせ</div>
        <div class="card-body">
          <%= @group.notice %>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">リンク集</div>
        <div class="card-body">
          
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">参加メンバー
          <%= link_to '追加', new_group_invite_path(group_id: @group.id), {class: 'text-white float-right'} %>
        </div>
        <div class="card-body">
          <% @group.group_accounts.each do |group_account| %>
            <% user = User.find_by(account_id: group_account.account_id) %>
            <div>
              <img src="<%= "/user_images/#{user.image_name}" %>" width="30">
              <%= link_to user.name, user_path(user.id) %>
            </div>
          <% end %>
        </div>
      </div>
      <div>
        <a href="">更新履歴を表示</a>
      </div>
    </div>

    <div class="col-8">
      <div class="d-flex justify-content-between">
        <div><small>新着順に表示 | <a href="#">分類ごとに表示</a></small></div>
        <div><small>未読のみ | <a href="#">すべて</a></small></div>
      </div>

      <div class="card mb-3 border-0">
        <div class="card-header text-white bg-dark">プロジェクト
          <%= link_to raw('<i class="far fa-plus-square"></i> 登録'), new_group_project_path(group_id: @group.id), {class: 'text-white float-right'} %>
        </div>
        <%= render partial: "_group_modules/show_updates", locals: {project_updates: @project_updates} %>
      </div>
      
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">掲示板</div>
        <div class="card-body">
          
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header text-white bg-dark">共有フォルダ</div>
        <div class="card-body">
  
        </div>
      </div>
      <div class="card mb-3 border-0">
        <div class="card-header text-white bg-dark">イベント</div>
        <%= render partial: "_group_modules/show_calendar_updates", locals: {calendar_updates: @calendar_updates} %>
      </div>
    </div>

    <div class="col-2">
      <div class="card">
        <div class="card-header text-white bg-dark">
          タイムライン
        </div>
        <div class="card-body">

        </div>
      </div>
    </div>
  </div>
</main>